# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
# https://crontab.guru/

on:
  # the workflow will run once when the main branch was updated
  push:
    branches:
      - main
  schedule:
    # POSIX cron syntax (daily 17:00 UTC), see https://crontab.guru/#0_17_*_*_*
    - cron: "0 17 * * *"

jobs:
  hoyolab-checkin:

    name: "Hoyolab daily check-in"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Hoyolab check-in (Account 1)"
        uses: codemasher/hoyolab-daily-checkin-action@v1
        with:
          cookie: ${{ secrets.ACCOUNT1 }} # see get-token.js
          genshin: true
          honkai3rd: true
          starrail: true
          tearsofthemis: false
          # optional notification settings - you can safely remove these
          language: 'en-us'
          account-description: "Account 1"
          only-notify-failed: false
          discord-notify: true
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          discord-user-id: ${{ secrets.DISCORD_USER_ID }}

      # you can safely remove this step if you only have one account to run
      - name: "Hoyolab check-in (Account 2)"
        uses: codemasher/hoyolab-daily-checkin-action@main
        with:
          cookie: ${{ secrets.ACCOUNT2 }}
          language: 'en-us'
          account-description: "Account 2"
          only-notify-failed: false
          discord-notify: true
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          discord-user-id: ${{ secrets.DISCORD_USER_ID }}
          genshin: true
          honkai3rd: false
          starrail: false
          tearsofthemis: false
